{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "refael-nodejs.fullname" . }}
  labels:
    {{- include "refael-nodejs.labels" . | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - {{- if .Values.ingress.host }}host: {{ .Values.ingress.host | quote }}{{- end }}
      http:
        paths:
          {{- range .Values.ingress.paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "refael-nodejs.fullname" $ }}
                port:
                  number: {{ $.Values.service.port }}
          {{- end }}
{{- end }}
